### ISSUE TITLE
Readme file is not informative

### ISSUE THREAD

**Issue by oleggl8** [hadaromer/Unified-Raster#2]
Hi,
looks like u have very interesting project 
Could u please add more detailed info regarding the project in readme file

**Comment by hadaromer** [comment]
Hey! 
I appreciate your interest, the readme file updated - take a look.
The project is still in proggress, stay tuned :)

Omer

**Comment by oleggl8** [comment]
cool 
glad to see that project is a live :)

**Comment by da-be-da** [comment]
I'm sorry but i don't see any progress on this issue, Can you please reopen it?

**Comment by hadaromer** [comment]
Fixed
