### ISSUE TITLE
Bad practice to use alerts in SPA applications

### ISSUE THREAD

**Issue by oleggl8** [hadaromer/Unified-Raster#3]
#https://github.com/hadaromer/Unified-Raster/blob/587a8945952c20c0e272e7305dcb12909455dca7/src/App.js#L17

**Comment by oleggl8** [comment]
Any progress ...
Its very important for me

**Comment by hadaromer** [comment]
Hey,
sorry about the delay, i have added snackbar functionality.

https://github.com/hadaromer/Unified-Raster/blob/29cffeb80823450cf09974f3e715165d0cd3bfec/src/App.js#L19
