### ISSUE TITLE
Please move coordinate values to configuration

### ISSUE THREAD

**Issue by oleggl8** [hadaromer/Unified-Raster#4]
https://github.com/hadaromer/Unified-Raster/blob/587a8945952c20c0e272e7305dcb12909455dca7/src/Map/Map.js#L49

**Comment by hadaromer** [comment]
fixed :)

https://github.com/hadaromer/Unified-Raster/blob/b80684165f8f582277992bb69b9ee70745db62aa/src/Map/Map.js#L41
