### ISSUE TITLE
How are u going to run your application?

### ISSUE THREAD

**Issue by oleggl8** [hadaromer/Unified-Raster#5]
Are u going to create Docker? or u going to use any server? nginx?

**Comment by hadaromer** [comment]
Right now im using express.js for getting information about the layers that im showing on the map.

**Comment by oleggl8** [comment]
As i can see there is going to be server side with REST API that your react app will communicate with. My Q was more regarding who and how will serve your react SPA application?

Common scenario docker based on NGINX

**Comment by shimoncohen** [comment]
You are correct, the application is going to be docker based. In the future, it will be served by kubernetes platform host.
