### ISSUE TITLE
Why host is hard coded?

### ISSUE THREAD

**Issue by oleggl8** [hadaromer/Unified-Raster#6]
https://github.com/hadaromer/Unified-Raster/blob/0976bebae75550b7a45ea44b0960565904017b29/src/App.js#L15

**Comment by oleggl8** [comment]
> https://github.com/hadaromer/Unified-Raster/blob/0976bebae75550b7a45ea44b0960565904017b29/src/App.js#L15

there should be configuration care in the project , check config js npm package

**Comment by shimoncohen** [comment]
Issue fixed in 5692eee2b3488f2e33a9bf38a62c1ce460f527da by @hadaromer.
https://github.com/hadaromer/Unified-Raster/blob/db05b4bda4a05c8f641efe664af8fe8f6e91a889/src/General/Config.js#L1
From what we read the config package from npm is not used in react apps.
